name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - image: ubuntu-24.04
            arch: x86_64
            ubuntu: ubuntu2404
          - image: ubuntu-24.04-arm
            arch: aarch64
            ubuntu: ubuntu2404
          - image: ubuntu-26.04
            arch: x86_64
            ubuntu: ubuntu2604
          - image: ubuntu-26.04-arm
            arch: aarch64
            ubuntu: ubuntu2604
    runs-on: ${{ matrix.image }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: stop update man-page
      run: |
        echo "set man-db/auto-update false" | sudo debconf-communicate
        sudo dpkg-reconfigure man-db
    - uses: actions/checkout@v7
      with:
        repository: 'wx257osn2/apptainer-proot'
        ref: ${{ github.ref_name }}
    - name: build
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libseccomp-dev libtalloc-dev libattr1-dev libprotobuf-c-dev libfuse3-dev zlib1g-dev liblzo2-dev liblz4-dev liblzma-dev libzstd-dev uuid-dev autoconf automake libtool pkg-config curl zstd patch
        ./mconfig -p /opt/apptainer --without-suid
        pushd ./builddir
        make -j $(nproc)
        make install
        popd
        mkdir -p deps
        ./scripts/download-dependencies ./deps
        rm ./deps/e2fsprogs*.tar.gz
        mkdir -p ./deps/e2fsprogs-e4f17380b2e5
        curl -fsSL https://github.com/wx257osn2/tytso-e2fsprogs/archive/e4f17380b2e5b8356ab9806689f780d386ce8e3e.tar.gz | tar -xz -C "./deps/e2fsprogs-e4f17380b2e5" --strip-component=1
        tar -czf "./deps/e2fsprogs-e4f17380b2e5.tar.gz" -C "./deps" "e2fsprogs-e4f17380b2e5"
        rm -r "./deps/e2fsprogs-e4f17380b2e5"
        pushd deps
        ../scripts/compile-dependencies .
        ../scripts/install-dependencies /opt/apptainer/libexec
        popd
        tar -C /opt -cf ./${{ matrix.ubuntu }}-${{ matrix.arch }}.tar.zst --use-compress-program="zstdmt -18" apptainer
    - uses: actions/upload-artifact@v7
      with:
        name: archive-${{ matrix.ubuntu }}-${{ matrix.arch }}
        path: ./${{ matrix.ubuntu }}-${{ matrix.arch }}.tar.zst
  deploy:
    runs-on: ubuntu-slim
    needs: build
    permissions:
      contents: write
    steps:
    - run: |
        version=$(echo ${{ github.ref }} | sed 's@refs/tags/@@g')
        echo "apptainer_version=${version}" >> $GITHUB_ENV
    - parallel:
      - uses: actions/download-artifact@v8
        with:
          name: archive-ubuntu2404-x86_64
      - uses: actions/download-artifact@v8
        with:
          name: archive-ubuntu2404-aarch64
      - uses: actions/download-artifact@v8
        with:
          name: archive-ubuntu2604-x86_64
      - uses: actions/download-artifact@v8
        with:
          name: archive-ubuntu2604-aarch64
      - run: |
          cat << 'EOF' > install.bash
          #!/bin/bash
          set -euxo pipefail
          curl -sSL https://github.com/wx257osn2/apptainer-proot/releases/download/${{ env.apptainer_version }}/ubuntu$(bash -c 'source /etc/os-release; echo ${VERSION_ID//./}')-$(uname -m).tar.zst | tar -C ${1:-"${HOME}/.local"} -x --use-compress-program="pzstd"
          EOF
      - run: |
          cat << 'EOF' > release_notes
          ```
          $ which tar
          $ which curl
          $ which pzstd
          $ curl -sSL https://github.com/wx257osn2/apptainer-proot/releases/download/${{ env.apptainer_version }}/install.bash | bash -s -- /path/to
          $ /path/to/apptainer/bin/apptainer --version
          ```
          EOF
    - uses: softprops/action-gh-release@v3
      with:
        files: |
          ubuntu2404-x86_64.tar.zst
          ubuntu2404-aarch64.tar.zst
          ubuntu2604-x86_64.tar.zst
          ubuntu2604-aarch64.tar.zst
          install.bash
        body_path: release_notes
